ansible/roles/frontend/defaults/main.yml, ansible/roles/frontend/files/build_frontend.sh, ansible/roles/frontend/tasks/deploy.yml, ansible/roles/frontend/vars/development.yml.dist
* Define new `frontend_use_restricted_assets` variable (boolean).
* If True, copy private key; fetch private asset gem; build as normal; delete key.
* If False, just build the frontend without the private asset gem.
* See dpla/frontend#45 for related frontend changes.
=> Improve frontend private asset handling

README.md, ansible/playbooks/dbnodes.yml, ansible/playbooks/elasticsearch.yml, ansible/playbooks/pre_post_tasks/api_pretasks.yml, ansible/playbooks/reboot_dbnodes.yml, ansible/playbooks/reboot_elasticsearch.yml, ansible/playbooks/reboot_siteproxy.yml, ansible/playbooks/siteproxy.yml, ansible/roles/common/tasks/main.yml
- Require Ansible 1.8
- For reboots and loadbalancer pool operations, wait for connections
to drain before proceeding.
The 'state=drained' argument to wait_for is new with Ansible 1.8.
Allowing connections to drain means less likelihood of client errors.
I've tested this against my VMs and staging.
If you want to try this, there are two things to be aware of:
* You'll need to run the `common` role to install a new python package, `psutil`, on the inventory hosts.
* You'll have to comment out the deb package source in `ansible/roles/dbnode/templates/cloudand.list.j2` because of an unrelated issue with Cloudant yanking the BigCouch package from its former location.  Comment this out if you run the `common_staging.yml` or `dbnodes_staging.yml` playbooks.  If you run `common_staging.yml` you …
=> Upgrade Ansible for connection draining support

ansible/roles/dbnode/tasks/main.yml, ansible/roles/dbnode/templates/cloudant.list.j2
Provide .deb package files to download, because the packages that we
used to fetch from the Cloudant repository have been removed.
Though we're going to stop using BigCouch soon, we have to fix this so that new installations of dev VMs with the legacy system don't fail.
=> Fix BigCouch installation

ansible/roles/dbnode/tasks/main.yml
If the old apt source list file is still present, it will cause
errors with package upgrades.  The file used to be necessary for our
BigCouch installation and might be present on systems that have existed
before we removed it.
=> Ensure that Cloudant package list has been removed

ansible/playbooks/pg_maintenance_off.yml, ansible/playbooks/pg_maintenance_on.yml, ansible/playbooks/reboot_postgresql.yml
Allow for manual initiation and disabling of maintenance mode outside of a reboot.
Also add clearing of proxy cache, which was necessary but missing.
This is a minor change I had hanging around and had forgotten about until now, but will be convenient to have merged before making some upcoming changes to production.  It makes it more convenient to put the frontend into maintenance mode for something other than a server reboot.  It also fixes the fact that the proxy cache was not being cleared.
=> Make PostgreSQL maintenance playbooks more flexible

ansible/roles/omeka/defaults/main.yml
Minor change that's caused us some snags in the past.
=> Exhibitions: deploy master by default

ansible/playbooks/deploy_ingestion_app.yml, ansible/playbooks/deploy_ingestion_app_development.yml, ansible/playbooks/deploy_ingestion_app_production.yml, ansible/playbooks/deploy_ingestion_app_staging.yml
This adds discrete playbooks for deploying the ingestion application, without performing the role's other provisioning tasks.
=> Add standalone ingestion app deployment playbooks

ansible/roles/api/files/build_api.sh, ansible/roles/api/files/copy_local_app.sh, ansible/roles/frontend/files/build_frontend.sh, ansible/roles/frontend/files/copy_local_app.sh, ansible/roles/ingestion_app/files/build_ingestion.sh, ansible/roles/ingestion_app/files/copy_local_app.sh, ansible/roles/wordpress/files/build_wordpress_local.sh, ansible/roles/wordpress/files/sync_to_siteroot.sh
Rsync is used in various deployment scripts to copy files between
source, build, and target directories.
When rsync is called with `--checksum`, the `-u` option should
not be passed, because this overrides the desired checksum
behavior.
This was causing  files modified on the server more recently than their
sources in the local development working copy to fail to be overwritten.
In at least one case, we modify a Gemfile in the server's build
directory after it's copied there, which results in its timestamp being
newer than that of the source.  The next time it's deployed, it will
fail to be copied if the `-u` switch is given to rsync.
Here is an example of rsync's behavior with and without `-u`, combined
with `checksum`:
```bash
$ mkdir a b
$ echo line1 > a/file
$ rsync -a a/ b
$ cat …
```
=> Fix incorrect rsync options for deployments

ansible/roles/api/files/copy_local_app.sh, ansible/roles/api/tasks/deploy.yml, ansible/roles/frontend/files/copy_local_app.sh, ansible/roles/frontend/tasks/deploy.yml, ansible/roles/ingestion_app/files/copy_local_app.sh, ansible/roles/ingestion_app/tasks/deploy.yml
Fix the population of build directories during deployments in the
development environment to avoid errors in some cases when switching
between local-filesystem and git deployments.
This also preserves separate directories for git and local build
directories so that they can be better analyzed independently of
one-another and so that they should be faster to rsync upon subsequent
deployments.
=> Improve cooperation between local and git deployments

ansible/roles/munin_master/defaults/main.yml, ansible/roles/munin_master/templates/munin.conf.j2
Add munin_always_send and munin_always_send_priorities, which govern
whether Munin sends repeated alert messages if the alert's state has
not changed.
=> Add param for controlling Munin alert sending

ansible/roles/common_php/tasks/main.yml
Omeka requires php5-cli to run background jobs; this is not adequately represented in Omeka's documentation.
This fixes an issue where the Omeka CSV Import plugin was not working properly.
=> Install php5-cli for common_php role [fixes #7788]

ansible/group_vars/ingestion, ansible/group_vars/ingestion_app, ansible/ingestion, ansible/roles/common/defaults/main.yml, ansible/roles/common/handlers/main.yml, ansible/roles/common/tasks/main.yml, ansible/roles/common/templates/etc_sysctl.d_60-overcommit.conf.j2
See http://www.win.tue.nl/~aeb/linux/lk/lk-9.html
See http://www.etalabs.net/overcommit.html
The default for vm.overcommit_memory is the Linux kernel default of 0,
for the standard heuristic.  The ingestion servers use 2, to allow them
to go a little crazier with malloc and, I suppose, potentially forking
new processes.
The development VM `dev2` is given an overcommit_ratio of 95 to allow it to allocate a little more memory, because it doesn't have a swap partition.  (Some memory is reserved for kernel buffer and block caches.)  I'm not sure if this is the best setting, but let's see how it works.
=> Set Linux kernel params for memory overcommitment

ansible/roles/ingestion_app/templates/config_settings.local.yml.j2
Add an `elasticsearch` section to Heidrun's settings.local.yml
This will need to be in-place before https://github.com/dpla/KriKri/pull/131 is merged in and deployed.
=> Add `elasticsearch` to ingestion app settings

ansible/roles/marmotta/templates/system-config.properties.j2
Disables the LDCache module, which attempts to fetch remote resources through dereferencing. This will reduce the number of outgoing requests from our Marmotta instance, and may speed up save and query performance.
LDCache is known to at least have some performance implications, as described [here](https://github.com/apache/marmotta/blob/develop/platform/ldcache/marmotta-ldcache-common/src/main/resources/config-defaults.properties#L23-L25).
=> Marmotta: disable LDCache module

ansible/roles/marmotta/tasks/main.yml, ansible/roles/marmotta/templates/etc_logrotate.d_nginx.j2
The default logrotate configuration for Nginx was not rotating the logs
quickly enough to address some disk space issues we have been seeing.
This changes the Nginx logs to rotate daily, with 7 days of logs being
retained.
=> [marmotta] Set up custom log rotation for Nginx

ansible/roles/api/templates/dpla.yml.j2
The API cache in contentqa should be clearable quickly; this moves the caching to use file-based caching.
=> Use file-based caching for API in contentqa

ansible/roles/tomcat_common/defaults/main.yml, ansible/roles/tomcat_common/tasks/main.yml, ansible/roles/tomcat_common/templates/etc_cron.d_prune-tomcat-access-logs.j2, ansible/roles/tomcat_common/templates/etc_default_tomcat7.j2, ansible/roles/tomcat_common/templates/etc_logrotate.d_tomcat7.j2
- Prune access_log logs that were not being deleted
- Add parameters for age of "catalina" and AccessLogValve logs
- Change "catalina" logs to rotate daily, instead of weekly
=> Improve Tomcat logfile rotation

ansible/roles/marmotta/templates/etc_nginx_sites-available_marmotta.j2
Update the configuration of the NGINX reverse-proxy for the marmotta
server, having it log request times in the access log.
=> Log Marmotta's NGINX proxy request time

ansible/group_vars/worker
Assign `kernel_vm_overcommit_memory` on the servers in the `worker`
inventory group.  This sets vm.overcommit_memory.
This was left out of commit 3bc3305d, as an oversight.  That commit
attempted to set this parameter to prevent problems with ingestion
processes requesting too much memory, something that is actually more
likely to happen on the `worker` servers.  I had apparently forgotten
that, though both the `worker` and `ingestion_app` inventory groups have
the `ingestion_app` role applied, they are separate groups, and require
separate `group_vars` files.
=> Assign kernel overcommit setting on workers

ansible/roles/site_proxy/templates/etc_nginx_sites_available_site-proxy.j2
Complements dpla/platform#37. This is necessary, since our JSON-LD `@context` URIs are referred to using `http://dp.la/api`.
=> [site proxy] Enable CORS for API redirects

ansible/playbooks/deploy_exhibitions_development.yml, ansible/playbooks/deploy_exhibitions_production.yml, ansible/playbooks/deploy_exhibitions_staging.yml
In the Omeka (exhibitions) deployment playbook, ensure that role-local
variables get included for the given environment ("level").
=> Fix variable inclusion, Omeka deployment

ansible/.gitignore, ansible/roles/api/vars/.gitignore, ansible/roles/common/vars/.gitignore, ansible/roles/dbnode/vars/.gitignore, ansible/roles/elasticsearch/vars/.gitignore, ansible/roles/frontend/vars/.gitignore, ansible/roles/ingestion_app/vars/.gitignore, ansible/roles/marmotta/vars/.gitignore, ansible/roles/munin_master/vars/.gitignore, ansible/roles/mysql/vars/.gitignore, ansible/roles/omeka/vars/.gitignore, ansible/roles/postgresql/vars/.gitignore, ansible/roles/tomcat_common/vars/.gitignore, ansible/roles/wordpress/vars/.gitignore, ansible/vars/.gitignore
Add a `local` directory that will contain ancillary inventories and playbooks that use roles defined here in `automation`, but that should not exist in this repository.
To test this, try `git status` and verify that it doesn't reveal anything new.  You should not see any untracked files that weren't there before.  Note that operations with inventories other than `development` or `ingestion` will require passing `ansible-playbook` an `-i` option with the new location to the inventory file, under `local/inventory`.
This adds a `.gitignore` exclusion for a new `local` directory (which is up to the user to add) and makes various `.gitignore` files more flexible.
=> Add local directory

ansible/roles/omeka/defaults/main.yml, ansible/roles/omeka/tasks/deploy.yml, ansible/roles/omeka/templates/etc_nginx_sites_available_omeka.j2
- Allow the `omeka` role to work outside of our normal production
environment, by adding the skip_site_proxy_cache variable, which makes
the installation independent of the `site_proxy` role.
- Add an NGINX redirect for a standalone exhibitions server, sending
requests for `/` to `/exhibitions/`.
=> Improve Omeka deployments

ansible/playbooks/exhibitions_development.yml, ansible/playbooks/exhibitions_production.yml, ansible/playbooks/exhibitions_staging.yml
Add provisioning and configuration playbooks for `omeka' role
(Exhibitions).  There were playbooks for deploying the application, but
not for the other provisioning and configuration tasks (the role's
main.yml).
=> Add missing playbooks for Exhibitions

ansible/roles/omeka/templates/etc_nginx_sites_available_omeka.j2, ansible/roles/site_proxy/templates/etc_nginx_sites_available_site-proxy.j2
Change proxy caching of the Exhibitions site to forego caching of HTML,
but keep caching static files.
Remove an `expires max` directive from the cms server's virtual host for
`omeka`, to allow a browser "refresh" to cause the proxy to hit the CMS
with an if-modified-since request, achieving a nicer balance between
caching and refreshability.
=> Change Exhibitions cache strategy

README-ingestion2.md, ansible/roles/ingestion_app/defaults/main.yml, ansible/roles/ingestion_app/files/build_ingestion.sh, ansible/roles/ingestion_app/tasks/deploy.yml, ansible/roles/ingestion_app/templates/config_environments_test.local.yml.j2, ansible/roles/ingestion_app/templates/database.yml.j2
These changes facilitate development on `heidrun` and `krikri` using the VMs.
* A new "fast deployment" variable has been added, that speeds up application code-only deployments.
* Configuration and database problems have been fixed, allowing spec tests to be run on the dev2 VM.
Now that I can run `bundle exec rake ci` on `dev2`, I occasionally encounter the following error:
```/home/dpla/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/net-http-persistent-2.9.4/lib/net/http/persistent.rb:641:in `rescue in connection_for': connection refused: localhost:8983 (Net::HTTP::Persistent::Error)```
This happened once or twice and I haven't been able to reproduce it.  I mention it here in case it speaks of some configuration change that could be made in this project.
=> Improve, fix heidrun deployments

ansible/roles/common/tasks/main.yml
Add a task to ensure that specific Munin plugins will always be
installed.
Two network plugins have been explicitly enabled, which are enabled by
default on Ubuntu 14.04, but not 12.04.
=> Add task to ensure common Munin plugins are enabled

ansible/ingestion
Add queues for mapping, enrichment, and indexing.
Allow just one worker for each queue.
=> Add queues to development VM inventory

ansible/roles/ingestion_app/tasks/deploy.yml, ansible/roles/ingestion_app/templates/config_solr.yml.j2
At deployment, update the config/solr.yml file in `heidrun` with
appropriate values for our environment.
The development and production values were previously getting set
with "http://127.0.0.1:8983/solr"
=> Fix the config/solr.yml file deployed with heidrun

ansible/roles/ingestion_app/templates/heidrun.god.j2
Have god start resque workers with the $HOME environment variable
correctly set.
I noticed that my workers in my development VMs were not able to start
without this being set.  There were errors in
/opt/heidrun/log/worker.log indicating:
ArgumentError: couldn't find HOME environment -- expanding `~'
=> Add HOME environment var to god config

README-ingestion2.md, ansible/roles/ingestion_app/handlers/main.yml, ansible/roles/ingestion_app/tasks/deploy.yml
- Delete Solr index when there is a schema change.
- Reload the Solr core instead of restarting Tomcat.
There is no standalone playbook for clearing the Solr index, which would
be nice, but which would take longer to put together than I can afford
right now, because I'd have to spend more effort to avoid duplicating
code in that case.
After clearing the index, you have to run a new indexing operation,
which is out of the scope of the `automation` project.  Just note that
that has to happen.  It seems that a first-time indexing run after the
schema is changed, the index is deleted, and the Solr core is restarted
requires a reload of the core again for the added documents to show up.
I don't have an explanation for that, and I'm not sure whether it has to
do with deleting the index, or …
=> Improve Solr index and configuration operations

README.md, Vagrantfile.dist, Vagrantfile.ingestion2, ansible/playbooks/elasticsearch.yml
This fixes a handful of minor issues I ran into when building the automation project from scratch today.
- Removes a duplicate bullet point from `README.md`
- Forces Vagrant to use the default `insecure_private_key`. Some versions overwrite that key on new machines by default, breaking Ansible's SSH initial login as the `vagrant` user.
- Fixes an error with the elasticsearch jobs in `development`.
=> Minor Fixes for a From-scratch Run

ansible/roles/postgresql/defaults/main.yml, ansible/roles/postgresql/templates/postgresql.conf.j2
Use a parameter to set random_page_cost.  This is a minor change that
won't result in a major impact, but it's easy to make.  A lower
random_page_cost is more appropriate for SSD drives or Amazon EBS
volumes.
=> Set PostgreSQL random_page_cost

ansible/roles/marmotta/templates/system-config.properties.j2
Per discussion on 2015-06-25, we are disabling the reasoner module for Marmotta,
which will allow us to partition Marmotta's database tables more effectively.
(cc @markbreedlove - please add any salient details)
=> Disable Marmotta reasoner

ansible/roles/api/files/build_api.sh, ansible/roles/frontend/files/build_frontend.sh, ansible/roles/ingestion_app/files/build_ingestion.sh
In scripts that update Ruby gem bundles, use `bundle update` instead of
`install`, in order to upgrade versions of gems.
See http://bundler.io/v1.3/man/bundle-update.1.html
=> Change bundle install to bundle update

ansible/roles/marmotta/tasks/main.yml, ansible/roles/marmotta/templates/etc_nginx_sites-available_marmotta.j2
Set the maximum request body size, client_max_body_size, in the virtual host of the NGINX reverse proxy in front of Marmotta.  The NGINX default of 1MB has been preventing larger records from being PUT.
See the comment in the template about other Tomcat parameters, but this is at least a step.  After the change, I am able to harvest a record that used to be refused due to its large size.  I've set the maximum request body size to 8 MB, which I think is pretty generous.  I haven't been able to determine Tomcat's default maximum request body size for a PUT request.
=> Set max. request body size, Marmotta NGINX proxy

ansible/group_vars/geocoder, ansible/playbooks/geocoder.yml, ansible/playbooks/geocoder_production.yml, ansible/roles/geocoder/defaults/main.yml, ansible/roles/geocoder/files/etc_logrotate.d_twofishes, ansible/roles/geocoder/handlers/main.yml, ansible/roles/geocoder/tasks/main.yml, ansible/roles/geocoder/templates/etc_init.d_twofishes.j2, ansible/roles/geocoder/vars/.gitignore, ansible/roles/munin_master/vars/main.yml
Add geocoder role, which runs the Twofishes service for geocoding spatial data during ingestion enrichments.
Provisions are only made for a production server.  I'm hoping that this will work out.  Fitting it into one of the development VMs is either not practical, or will require extra work to deal with Twofishes's memory needs.
=> Add geocoder role

ansible/roles/common_php/templates/php.ini.j2, ansible/roles/omeka/templates/application_config_config.ini.j2, ansible/roles/omeka/templates/etc_nginx_sites_available_omeka.j2, ansible/roles/site_proxy/templates/etc_nginx_sites_available_site-proxy.j2, ansible/roles/wordpress/templates/etc_nginx_sites_available_wordpress.j2, ansible/roles/wordpress/templates/etc_php5_fpm_pool.d_wp.conf.j2
Increases the maximum upload size for Omeka and WordPress both within the Nginx virtual hosts used by the application and those used by the site proxy nodes. Fixes the `413 Request Entity Too Large` errors. 
Fixes [#7851](https://issues.dp.la/issues/7851).
=> Bump PHP upload_max_filesize/post_max_size to 50 MB (fixes #7851)

ansible/roles/common_web/defaults/main.yml, ansible/roles/common_web/templates/etc_nginx_nginx.conf.j2, ansible/roles/site_proxy/defaults/main.yml, ansible/roles/site_proxy/templates/etc_nginx_sites_available_site-proxy.j2
This changeset adds a few preliminary changes for parameterizing existing rate-limiting directives, and improving logging.  It then adds rate-limiting directives to place specific controls on the bookshelf, which makes relatively expensive search queries with lots of facets.
=> Rate-limit the bookshelf section of the frontend application

ansible/roles/site_proxy/templates/etc_nginx_sites_available_site-proxy.j2
TODO: determine whether and how to cache bookshelf responses.
HTML and JSON responses were being cached under the same
proxy_cache_key, leading to JSON being returned for the main bookshelf
page.  If caching is enabled, it should use the suggested
proxy_cache_key value to ensure that JSON and HTML do not get mixed up.
This is related to the frontend's design decision to have the same
resource return not only different representations given different
Accept: content types, but different objects (data), as well.
=> Disable proxy caching of bookshelf

ansible/playbooks/frontend.yml, ansible/playbooks/frontend_development.yml, ansible/playbooks/frontend_production.yml, ansible/playbooks/frontend_staging.yml
Add playbooks to provision and configure the operating environment and
services surrounding the frontend app.
A playbook already existed to deploy the frontend, but there was no
playbook dedicated to configuring Unicorn, NGINX, package dependencies,
and so on.
This playbook runs everything for the frontend role, so it will
configure as well as deploy it.
=> Add playbooks to configure frontend app

ansible/roles/ingestion_app/tasks/main.yml
This is significant in production, or wherever the RAILS_ENV should not be the default, `development`.  If you are using the wrong RAILS_ENV (e.g. `development` on a production system), various settings could be off; for example (in my experience) you might enqueue jobs that get sent to the wrong redis queue, where they will not be picked up by the workers, (e.g. which are listening on the `production` queue).
=> Set dpla account's RAILS_ENV for ingestion app

ansible/roles/frontend/handlers/main.yml, ansible/roles/frontend/tasks/deploy.yml
The frontend app. is configured in settings.local to use memcached.  It seemed to help last week when troubleshooting the frontend app to restart memcached at one point.
=> Add memcached restart to frontend deployment

README-ingestion2.md, README.md, ansible/roles/api/tasks/deploy.yml, ansible/roles/frontend/tasks/deploy.yml, ansible/roles/ingestion_app/tasks/deploy.yml, ansible/roles/omeka/tasks/deploy.yml, ansible/roles/solr/files/install_solr.sh
This PR fixes a few things:
* We expect Ansible 1.9, which is to say, we don't fail when run with this version.   The documentation has been updated to reflect 1.9 as the expected version, and the `git` module invocations have been updated to use `force=true`, because the default for that module changed between `1.8` and `1.9`.  Ansible 1.9.2 contains an important security fix that affects any lower version.
* The download base URL for Solr is fixed.  It was only good for the most recent patchlevel of the desired version, leading to potential 404 errors when trying to download the package that's specified in our configuration.
* The README documentation has been improved with some advice on making installations run more smoothly.
These changes have been tested with Ansible 1.9, with:
* …
=> Expect Ansible 1.9, plus other fixes

ansible/roles/marmotta/templates/etc_nginx_sites-available_marmotta.j2
Make the NGINX proxy for Marmotta do keepalive connections.
I am curious to see if this makes any difference.  It seems that it should result in less latency, because fewer connections to Marmotta will have to be established.
=> Add NGINX keepalive, marmotta proxy

ansible/roles/marmotta/files/tunedb.sh, ansible/roles/marmotta/tasks/main.yml
Disable this script, because it should not work on a new installation,
where tablespaces have not been created.  Tablespace creation is still
something under the manual control of a DBA.  The script is just
disabled now, and needs to be modified to iterate over existing
tablespaces, if they exist.
The tuning script has been preserved, of course, and is still useful if it's copied and modified.
=> Temporarily disable marmotta db tuning script

ansible/roles/api/files/build_api.sh, ansible/roles/api/files/copy_local_app.sh, ansible/roles/frontend/files/build_frontend.sh, ansible/roles/frontend/files/copy_local_app.sh, ansible/roles/ingestion_app/files/build_ingestion.sh, ansible/roles/ingestion_app/files/copy_local_app.sh, ansible/roles/omeka/files/build_exhibitions.sh, ansible/roles/omeka/files/copy_local_app.sh, ansible/roles/wordpress/files/build_wordpress_local.sh, ansible/roles/wordpress/files/sync_to_siteroot.sh
Fix the options given to rsync in the Exhibitions build script, to make sure that it selects files based on their checksums.  Timestamps must be ignored due to potential problems in development if one switches back and forth between locally-modified and downloaded copies of files.
Elsewhere, in other scripts, the -I (ignore timestamp) option has been added just for clarity, even when timestamps would have been ignored due to the --checksum option being given.
=> Fix rsync switches in Exhibitions and elsewhere

ansible/roles/tomcat_common/defaults/main.yml, ansible/roles/tomcat_common/handlers/main.yml, ansible/roles/tomcat_common/tasks/main.yml, ansible/roles/tomcat_common/templates/etc_munin_plugin_conf_d_zzz-tomcat.j2, ansible/roles/tomcat_common/templates/tomcat-users.xml.j2
* Adds a `tcmunin` user for Tomcat that only has access to the status pages in Tomcat Manager.
* Add Munin plugin-related tasks for Tomcat (installs dependencies, builds template to generate plugin configuration, and symlinks plugins into appropriate location).
=> Configure Tomcat plugin for Munin (fixes #7900)

ansible/roles/marmotta/templates/etc_nginx_sites-available_marmotta.j2
This reverts commit bcc646c3ab06688f034561997728722bbe500245.
dpla/automation#104 (Add NGINX keepalive, marmotta proxy) introduced an issue wherein upon nginx starting, it spits out an error:
```
2015/08/26 19:12:48 [emerg] 21963#0: invalid parameter "max_conns=200" in /etc/nginx/sites-enabled/marmotta:3
```
`max_conns` is only available with Nginx Plus (their commercial offering) based upon the subtle message in the documentation:
<http://nginx.org/en/docs/http/ngx_http_upstream_module.html#down>
=> Revert "Add NGINX keepalive, marmotta proxy" (refs #7903)

ansible/roles/api/tasks/deploy.yml, ansible/roles/frontend/tasks/deploy.yml, ansible/roles/ingestion_app/tasks/deploy.yml
Remove pid and socket files during deployments, after the shutdown step, in case these files were left around from an earlier failure.  Their presence will cause the startup to fail after the build step is complete.
=> Clean up stale Unicorn files

ansible/roles/api/files/build_api.sh, ansible/roles/frontend/files/build_frontend.sh, ansible/roles/ingestion_app/files/build_ingestion.sh, ansible/roles/pss/files/build_pss.sh
See https://issues.dp.la/issues/7840
This fixes issues with newly-added gems not installing, but ensures that deployments install the latest bugfix releases of correctly-pinned gems.
=> Fix ruby bundle installations and upgrades

ansible/roles/marmotta/files/tunedb.sh, ansible/roles/postgresql/defaults/main.yml, ansible/roles/postgresql/templates/postgresql.conf.j2
Add variables for some PostgreSQL configuration settings -- and adjust others -- that govern write performance. Change the configuration of the `bgwriter`, checkpointing, and locking. Enable logging for locks, checkpoints, and autovacuuming.
This has been tested with our `development` and `ingestion` inventories to the extent of making sure the playbook runs successfully. The settings have been used in our staging and production environments, with overrides for certain variables.
=> Improve PostgreSQL configuration for write performance

ansible/roles/ingestion_app/tasks/deploy.yml, ansible/roles/pss/tasks/deploy.yml
This addresses issues where assets were not being loaded, e.g. for the
primary-source-sets application and Heidrun.
=> Set RAILS_ENV when running Rails 4.x build scripts

ansible/playbooks/pg_maintenance_off.yml, ansible/playbooks/pg_maintenance_on.yml
Add the Primary Source Sets app to those Rails apps that are connected to PostgreSQL and that need to be taken offline during PostgreSQL maintenance.
=> Add pss to roles that have turnout maintenance mode

ansible/roles/ingestion_app/tasks/deploy.yml
Change `pss_rails_env` to `ingestion_app_rails_env`
Causes an error due to the variable not being defined when run with defaults (without it being overridden).
=> Fix variable name

README-ingestion2.md
* Add step for configuring locale before running subsequent package  installations.  Especially necessary to get the right encodings of  PostgreSQL's system databases.
* Add instruction in Ingestion 2 Readme to download Ubuntu 14.04 LTS box  in addition to 12.04.
The locale and encoding instructions are important to have in-place before merging some upcoming changes that perform a PostgreSQL 9.4 upgrade.
=> Improve installation instructions

ansible/roles/solr/files/install_solr.sh
Add the symlink `/var/lib/tomcat7/solr -> /opt/solr/dpla/solr` to fix an error in starting up Solr.
This fixes a problem that errors out the provisioning of a new Ingestion 2 development VM.
Solr was complaining in the development environment that it could not locate /var/lib/tomcat7/solr/collection1/conf/solrconfig.xml, and this was causing it not to start.
Why this was never encountered before is a bit of a mystery, and our production and staging environments have got by without this symlink. It's possible that the change in behavior is either due to the development system on which this was encountered having the most up-to-date system packages as possible, having been newly-installed, and one of these introducing some kind of relevant change; or that there was some change related to …
=> Add symlink to fix Solr startup error

ansible/playbooks/pg_maintenance_off.yml, ansible/playbooks/pg_maintenance_on.yml, ansible/playbooks/reboot_postgresql.yml, ansible/roles/api/defaults/main.yml, ansible/roles/api/templates/database.yml.j2, ansible/roles/frontend/defaults/main.yml, ansible/roles/frontend/templates/database.yml.j2, ansible/roles/ingestion_app/defaults/main.yml, ansible/roles/ingestion_app/templates/database.yml.j2, ansible/roles/pss/defaults/main.yml, ansible/roles/pss/templates/database.yml.j2
For various roles, add variables that allow for database hosts that exist outside of the inventory.  A good example is an Amazon RDS database instance that's not used in development.
The variables default to false so that normally the PostgreSQL database host is used.
To verify the behavior, you should be able to run `ansible-playbook` with `-C -D` and observe no changes to the `database.yml` config files, except for the removal of one line that I sneaked in there to remove a bogus property `hostname` from the `ingestion_app` file.
If you override something like `api_alternate_db_host` you should be able to see a change being proposed to the `database.yml` file with `-C -D`.
=> Allow setting of non-inventory database host

ansible/group_vars/all.dist
A new from-scratch deployment fails if you're just copying `group_vars/all.dist` to `group_vars/all`. There is no default value for the `pss_app_port` variable.
=> Set default port for PSS application

README.md, ansible/group_vars/all.dist, ansible/roles/frontend/defaults/main.yml, ansible/roles/frontend/files/build_frontend.sh, ansible/roles/frontend/tasks/deploy.yml, ansible/roles/pss/defaults/main.yml, ansible/roles/pss/files/build_pss.sh, ansible/roles/pss/tasks/deploy.yml
Add the variable `frontend_include_branding`, which governs whether the private dpla_frontend_assets gem is included for branding-related assets.  This defuaults to false.
Addresses one of the problems raised in https://github.com/dpla/automation/issues/117
There's a known issue mentioned in the comments of `build_frontend.sh`, but this is as good as it gets for now.  This prevents non-DPLA staff from running into build errors.
=> Install frontend assets only if requested

Vagrantfile.ingestion2, ansible/ingestion, ansible/roles/ingestion_app/defaults/main.yml
Reduce the amount of memory taken by Ruby processes in the 'ingestion' inventory for Ingestion 2 by reducing the number of processes.
Also give a little more memory to the 'dev2' VM in the Vagrantfile.
The worker processes could be dropped to just one, but I figure that it could be useful in development to make sure that the system works with concurrently-running processes.
=> Fix VM memory overallocation

ansible/roles/geocoder/templates/etc_init.d_twofishes.j2
Fix the init script to export the LANG locale environment variable, which fixes an error with the startup of twofishes, where it is not happy trying to read its database with the ASCII encoding.  It should try to use UTF8.
The `twofishes` init script was failing to start `twofishes` upon reboot.
=> Make twofishes start with system locale

ansible/files/install_ruby_tools.sh
Add `DISABLE_SPRING=1` to the `dpla` user's `.bashrc` wherever we set up Ruby.  We've always had problems running the Rails console whenever Spring has been running.  This is mostly a development issue.
I chose `install_ruby_tools.sh` because that's where other Ruby-related things are already set up, like `rbenv` and `bundler`.
=> Disable Spring wherever we use Ruby

ansible/playbooks/reboot_elasticsearch.yml
Change the invocation of a local action to run the set-allocation.sh script in order for the es_cluster_loadbal variable to be inherited from the relevant group_vars file.
This fixes an error about that variable being undefined. This issue was introduced back when the variables were rearranged.
=> Fix undefined variable, elasticsearch reboot

ansible/central_all.yml, ansible/roles/aws_postfix/templates/aliases.j2, ansible/roles/exporter/defaults/main.yml, ansible/roles/exporter/files/export-provider.sh, ansible/roles/exporter/tasks/main.yml, ansible/roles/exporter/templates/aws_config.j2, ansible/roles/exporter/templates/aws_credentials.j2, ansible/roles/exporter/templates/etc_cron.d_export-providers.j2
This script generates and uploads Bulk Download files straight from the Elasticsearch index, and supercedes the file-generation functionality of the legacy [ingestion](https://github.com/dpla/ingestion) project.
This change includes the automation necessary to have it run automatically on the `central` server, if that exists.
The script is designed to be useful either on cron or as a tool for exporting individual files on command. As such, it can be run locally or on the server.
=> Add new Bulk Download file script

ansible/roles/ingestion_app/files/build_ingestion.sh
Change the rsync path arguments in the build script for heidrun, so that
heidrun-mappings gets rsynced into place without its top-level
directory's contents.  Only the `heidrun` directory needs to be
transferred, and the changes suggested by
https://github.com/dpla/heidrun-mappings/pull/28 will result in a `spec`
directory that will have files with `require` statements that will
result in load errors.
=> Change rsync paths for heidrun-mappings

ansible/roles/pss/defaults/main.yml, ansible/roles/pss/templates/settings.local.yml.j2
See https://github.com/dpla/primary-source-sets/pull/104
There are some new Primary Source Sets application mail settings that need to be configured.
See http://guides.rubyonrails.org/action_mailer_basics.html#action-mailer-configuration and http://api.rubyonrails.org/classes/ActionMailer/Base.html
We set a default of `file` for development, because we don't run a MTA on the development VMs.  Staging and production environments can override this with `sendmail` so that `/usr/sbin/sendmail` is used.
=> Add Primary Source Sets mail settings

ansible/roles/pss/defaults/main.yml, ansible/roles/pss/templates/settings.local.yml.j2
This removes an obsolete setting for the `primary source sets` application.
This addresses [ticket #8246](https://issues.dp.la/issues/8246).
This relates to [aws PR#35](https://github.com/dpla/aws/pull/35/files) and [pss PR#110](https://github.com/dpla/primary-source-sets/pull/110).
=> remove obsolete pss tag setting

ansible/roles/frontend/files/build_frontend.sh
Add these Ubuntu packages, because we've recently added the `sqlite3` gem to the `frontend` app for tests, and bundler wants to install it regardless of the environment.
=> Fix sqlite3 dependency, frontend app

ansible/roles/api/tasks/main.yml
`pkill -f` actually returns an error status if the process did not exist, although it prints "Killed" to the terminal (not stdout or stderr -- I'm not sure which file it goes to).
Interestingly, plain `pkill` (without -f) does _not_ print "Killed" if the process did not exist, and it exits with 1.
The status that `pkill -f` returns if the process did not exist is 137, if a SIGKILL (-9) fails.  See http://tldp.org/LDP/abs/html/exitcodes.html 
The ansible `command` module was giving the return code as 1 in this case, instead of 137. The `shell` module, on the other hand, returns -9, which is not what we'd expect (137) but is better than 1, which is
indistinguishable from other kinds of failures.
=> Fix pkill task to stop old delayed_job process

ansible/roles/ingestion_app/defaults/main.yml, ansible/roles/ingestion_app/tasks/deploy.yml, ansible/roles/ingestion_app/vars/main.yml
Parameterize the GitHub repositories that are used for `heidrun` and `heidrun_mappings`.  This allows us to do deployments into our test or development systems from forked repositories.
=> Allow alternate repos for ingestion

ansible/playbooks/reboot.yml
See https://issues.dp.la/issues/7834
Add missing inventory groups to the first play in `reboot.yml`.
=> Add missing inventory groups to reboot play

ansible/roles/pss/templates/settings.local.yml.j2
See https://github.com/dpla/primary-source-sets/pull/126
This is necessary for the change in that PR to be deployed, but it's harmless for the config file to be modified without it.
=> Add DPLA API key to primary-source-sets

ansible/roles/pss/defaults/main.yml, ansible/roles/pss/templates/settings.local.yml.j2
Add variable dedicated to Primary Source Sets' own DPLA API key. The application could want to have its own key, instead of using the same one as the frontend.
The default key is the same as `api_key` and is simply one of the dummy keys that's created by the `platform` app and used in development.
=> Add pss_api_key variable

ansible/roles/site_proxy/templates/etc_nginx_sites_available_site-proxy.j2
This addresses the distributed crawls we're seeing in production that are hammering the search cluster, and that are ignoring robots.txt (which specifies that `/search`, `/timeline`, `/map`, and `/bookshelf` shouldn't be crawled).
=> Block bad bot using Pcore-HTTP/v0.18.1, which ignores robots.txt

ansible/development, ansible/group_vars/all.dist, ansible/playbooks/dev_webapps.yml, ansible/playbooks/thumbp.yml, ansible/playbooks/thumbp_development.yml, ansible/playbooks/thumbp_production.yml, ansible/playbooks/thumbp_staging.yml, ansible/roles/frontend/templates/etc_nginx_sites-available_frontend.j2, ansible/roles/frontend/templates/settings.local.yml.j2, ansible/roles/omeka/templates/application_config_config.ini.j2, ansible/roles/site_proxy/defaults/main.yml, ansible/roles/site_proxy/templates/etc_nginx_sites_available_site-proxy.j2, ansible/roles/thumbp/defaults/main.yml, ansible/roles/thumbp/files/install_python.sh, ansible/roles/thumbp/handlers/main.yml, ansible/roles/thumbp/tasks/main.yml, ansible/roles/thumbp/templates/etc_init.d_thumbp.j2, ansible/roles/wordpress/templates/wp-config.php.j2
* Add thumbp role and playbooks.
* Configure site proxy NGINX for proxying thumbnail images.
* Remove X-Forwarded-Proto coercion to 'http' in frontend's NGINX
config, which gets in the way of proxying SSL correctly.
* Change frontend settings.local to force 'https://' for API's base URL.
FIXME: This is probably not good.  REVIEW BEFORE SUBMITTING PR.
* Configure frontend settings.local to use scheme-relative base URL for
Wordpress and Wordpress widgets.
* Change Wordpress's wp-config.php to use SSL and scheme-relative URLs.
Hardcode 'https://' for API URL.
FIXME: This hardcoding is probably not good. REVIEW BEFORE SUBMITTING
PR.  (It won't work with development, using the VMs, yet.)
=> Add SSL capability and thumbnail proxy

ansible/roles/pss/templates/settings.local.yml.j2
This adds social media definitions to the primary source sets settings file.  They are used for various social media sharing features in the application.  These variables are used in other frontend applications, so the values for the variables are already defined.
I used this branch to run a test deployment of pss on staging and it worked as expected.
This impacts tickets [#8383](https://issues.dp.la/issues/8383) and [#8360](https://issues.dp.la/issues/8360).
=> add social media definitions to pss settings file

ansible/roles/marmotta/defaults/main.yml, ansible/roles/marmotta/files/marmotta.list, ansible/roles/marmotta/tasks/main.yml
Do not use package from stack.linkeddata.org. Download and install the .war file from apache.org.
The current failure of apt commands related to the bad package repo is blocking various infrastructure tasks.
Procedure: (to be added to release notes):
After updating `automation`, run the marmotta role itself with one of the dedicated playbooks. That should fix apt.
=> Fix Marmotta installation

ansible/roles/ingestion_app/files/copy_local_app.sh, ansible/roles/pss/files/copy_local_app.sh
In roles that copy local development working copies of applications, exclude `.vagrant` directories.
=> Do not copy `.vagrant` directories

ansible/ingestion
This fixes playbook runs for the `ingestion` inventory. The `thumbp` group was left out of https://github.com/dpla/automation/commit/efefe4b70d19e2f0d35fb89f85f1d82efb1c30bd , where it was only added to the `development` inventory.
This PR is to merge this change into a release-maintenance branch for version 2. The commit will be cherry-picked into `develop`. A release will be cut for v2.11.1 without it interfering with the pending release of version 3.
=> Add thumbp group to ingestion inventory

README-ingestion2.md, README-upgrade-3.0.md, README.md, ansible/dev_ingestion_all.yml, ansible/development, ansible/files/set-allocation.sh, ansible/group_vars/all.dist, ansible/group_vars/development.dist, ansible/group_vars/development_ingestion2.dist, ansible/playbooks/dev_loadbalancer.yml, ansible/roles/api/templates/dpla.yml.j2, ansible/roles/dev_loadbalancer/files/certificate.sh, ansible/roles/dev_loadbalancer/tasks/main.yml, ansible/roles/dev_loadbalancer/templates/haproxy.cfg.j2, ansible/roles/exporter/templates/etc_cron.d_export-providers.j2, ansible/roles/frontend/templates/settings.local.yml.j2, ansible/roles/ingestion_app/templates/config_settings.local.yml.j2, ansible/roles/omeka/templates/application_config_config.ini.j2, ansible/roles/site_proxy/templates/etc_nginx_sites_available_site-proxy.j2, ansible/roles/thumbp/templates/etc_init.d_thumbp.j2, ansible/roles/wordpress/templates/wp-config.php.j2
* Revise the dev_loadbalancer role so that HAProxy does SSL
* Update the `omeka` and `site_proxy` roles to allow the API to use SSL.
This PR is bound to the `frontend` changes currently under review as https://github.com/dpla/frontend/pull/83
=> Add development support for SSL

ansible/roles/pss/templates/settings.local.yml.j2
Add the API URL to primary source sets.  This relates to [PR#153 on PSS](https://github.com/dpla/primary-source-sets/pull/153) and [PR#42 on AWS](https://github.com/dpla/aws/pull/42).
=> add api url to pss

ansible/files/imagemagick_policy.xml, ansible/roles/common_php/handlers/main.yml, ansible/roles/common_php/tasks/main.yml, ansible/roles/frontend/handlers/main.yml, ansible/roles/frontend/tasks/main.yml, ansible/roles/omeka/tasks/main.yml
Add ImageMagick file: `/etc/ImageMagick/policy.xml`
The immediate concern is to fix the recently-announced ImageTragick exploit:
* https://imagetragick.com/
* https://bugs.launchpad.net/ubuntu/%2Bsource/imagemagick/%2Bbug/1578398
Note the conversation in the Ubuntu bugtracker in which the maintainer critiques the response from the ImageMagick upstream developers. Even though they have released a patch version (6.9.3-10) that they claim fixes the problem, the maintainer advocates that it is not sufficient. He provides some alternative approaches in http://www.openwall.com/lists/oss-security/2016/05/03/19, including the removal of the "delegate" functionality altogether, which does not seem appropriate.
The fact that this debate is going on indicates to me that it is a good idea for us to …
=> Add ImageMagick policy.xml file

ansible/roles/common/tasks/main.yml
Add the apt-show-versions package to the list that is installed by the common role. This adds the command of the same name, which is a little easier to use than `aptitude` for determining which packages need to be upgraded.
Example usage:
```
$ ssh you@server apt-show-versions -u
```
=> Add apt-show-versions utility to common role

ansible/playbooks/siteproxy.yml
Fix siteproxy playbook's "Wait for site proxy node to come back up" task so that it uses the correct port number for the wait_for module. The port number is different in the development environment that it is
elsewhere.
=> Fix siteproxy wait_for_host port number

ansible/roles/site_proxy/templates/etc_nginx_sites_available_site-proxy.j2
Redirect /wiki to the Wayback Machine for historical Berkman DPLA wiki.
=> Redirect /wiki to Wayback Machine

ansible/playbooks/deploy_frontend.yml, ansible/playbooks/frontend.yml, ansible/roles/frontend/files/copy_local_app.sh
* Add missing assignment of RAILS_ENV to frontend deployment
* Add exclusion for `public/assets` directory in local copy during frontend deployment.
This mostly affects development deployments.
=> Fix RAILS_ENV and rsync in frontend deployment

ansible/roles/pss/defaults/main.yml
Add a role default for `pss_api_url`, which was added in https://github.com/dpla/automation/commit/47625481760b6237c8d8520288ba771d6db72e12.
=> Add default for pss_api_url variable

ansible/roles/site_proxy/defaults/main.yml, ansible/roles/site_proxy/templates/etc_nginx_sites_available_site-proxy.j2
The goal of these changes was originally to cache `/thumb` resources, but it became apparent that we could do better in caching overall.
With this commit, and some work on the frontend app, it will be possible some day to forego the cache-purging that we usually do after a deployment.
* Reduce the number of proxy_cache_valid directives.
* Express 'expires' with date units.
* Remove redundant proxy_cache_valid directives. There was some variation, but not enough for it to be perpetuated.
* Rename shared memory zone from "staticfilecache" to "main_cache" because it's not simply a static file cache.
* Add "inactive" parameter to proxy_cache_path, which was defaulting to 10 minutes.
* Add note about proxy_cache_revalidate (NGINX sends If-Modified-Since to origin).  We can't use it because …
=> Improve NGINX cache configuration

ansible/roles/site_proxy/templates/etc_nginx_sites_available_site-proxy.j2
Make sure that all frontend and CMS sites are HTTPS.
Simplify redirect for "www" to use `return` instead of `rewrite`, while adding necessary `default_http_scheme`.
=> Redirect HTTP to HTTPS

ansible/roles/api/defaults/main.yml, ansible/roles/api/tasks/main.yml, ansible/roles/api/templates/database.yml.j2, ansible/roles/api/templates/dpla.yml.j2, ansible/roles/common/defaults/main.yml, ansible/roles/common/handlers/main.yml, ansible/roles/common/tasks/main.yml, ansible/roles/common/templates/etc_resolvconf_resolv.conf.d_base.j2, ansible/roles/common/templates/hosts.j2, ansible/roles/common/templates/munin-node.conf.j2, ansible/roles/common_web/tasks/main.yml, ansible/roles/elasticsearch_index/defaults/main.yml, ansible/roles/elasticsearch_index/tasks/main.yml, ansible/roles/elasticsearch_index/vars/main.yml, ansible/roles/frontend/tasks/main.yml, ansible/roles/postgresql/templates/pg_hba.conf.j2
* Add elasticsearch_index role. This will be incorporated into the development playbooks at a later point.
* Update some variables to default to False when they're not defined.
* Parameterize some configuration file parameters.
* Change common role to observe `all_group_name` for more flexibility with custom environments.
* Update common role to work better in dynamic inventory situations.
* Update postgresql role to use IP addresses instead of hostnames, for simplicity, and to avoid having to convert characters in dynamic-inventory hostnames.
* Tidy up various minor things.
=> Facilitate dynamic inventory and custom environments

ansible/roles/api/tasks/deploy.yml, ansible/roles/frontend/tasks/deploy.yml, ansible/roles/omeka/defaults/main.yml, ansible/roles/omeka/tasks/deploy.yml, ansible/roles/pss/tasks/deploy.yml, ansible/roles/wordpress/handlers/main.yml, ansible/roles/wordpress/tasks/main.yml
The NGINX cache configuration was changed in [v3.3.0](https://github.com/dpla/automation/releases/tag/v3.3.0) to make it safer for the cache to hold on to assets for a longer time. Pages that have to be fresh are no longer cached. We can therefore remove the role tasks that used to clear the cache. We still clear the Memcache cache where necessary, and we still have the playbook for doing it manually.
Addresses https://issues.dp.la/issues/8157
This could be something to try with one of your next deployments to verify how it goes.
=> Stop clearing NGINX proxy cache unnecessarily

ansible/roles/common/tasks/main.yml
Remove Landscape demo packages and Ubuntu Advantage Cloud guest advertisement, both of which clutter our MOTDs.
This is not high-priority, but fixes a longstanding minor annoyance.
=> Clean up MOTDs, remove demo packages

ansible/roles/ingestion_app/defaults/main.yml, ansible/roles/ingestion_app/tasks/deploy.yml, ansible/roles/ingestion_app/templates/geocode.yml.j2
Install the geocoder.yml configuration file that is needed by the Audumbla gem for enrichments in the ingestion application.
The installed configuration will not work in a development environment until the developer sets the `ingestion_app_geo_host` variable to something suitable (for example, in the `ansible/group_vars/development` file). The Twofishes geocoding server is not installed into the development VMs and must be managed separately.
Fixes https://issues.dp.la/issues/8455
=> Install geocoder config for ingestion

ansible/roles/api/files/build_api.sh, ansible/roles/frontend/files/build_frontend.sh, ansible/roles/ingestion_app/files/build_ingestion.sh, ansible/roles/pss/files/build_pss.sh
Add checks for return statuses in more of the commands issued in Rails deployment scripts.  There were rake tasks and other commands that could have failed silently and could have allowed deployments to proceed incorrectly.
=> Check for errors in more build script locations

ansible/roles/thumbp/tasks/main.yml, ansible/roles/thumbp/templates/etc_init.d_thumbp.j2
Instead of creating a subdirectory of `/var/run` that will get wiped out upon reboot, just put the pidfile in `/var/run` as other programs do.
=> Fix thumbp pidfile location

ansible/playbooks/thumbp.yml
Add the `do_deployment` variable to the `thumbp.yml` playbook.
This variable is evaluated by a number of roles, where it has no default by design. It was missing from the `thumbp` playbook, causing an error.
=> Add missing do_deployment var to thumbp playbook

ansible/roles/ec2_swapper/defaults/main.yml, ansible/roles/ec2_swapper/tasks/main.yml
This role is for EC2 instances that need to have swap partitions.
It is not used by any of the development inventories that ship with `automation`.
This method of creating a file with `fallocate` and mounting it as swap gives us the most consistency between different types of EC2 instances and will make automated provisioning easier.
=> Add ec2_swapper role

ansible/roles/site_proxy/templates/etc_nginx_sites_available_site-proxy.j2
Remove ipv6 listen directive from the site_proxy role's NGINX configuration. There is a loadbalancer in front of the site proxy under normal conditions, and it uses the siteproxy server's ipv4 address.
=> Remove ipv6 listen from site_proxy NGINX config

ansible/roles/common_web/defaults/main.yml, ansible/roles/common_web/tasks/main.yml, ansible/roles/common_web/templates/etc_logrotate.d_nginx.j2, ansible/roles/marmotta/tasks/main.yml
Add a task to configure logrotate for the NGINX logs, with a variable to govern the rotation period.
Remove the logfile rotation task and template from the Marmotta role.
Note that if different hosts need specific log rotation periods, they can be configured in host_vars files.
=> Configure logfile rotation in common_web role

ansible/roles/marmotta/templates/etc_security_limits.d_tomcat.conf.j2, ansible/roles/tomcat_common/defaults/main.yml, ansible/roles/tomcat_common/tasks/main.yml, ansible/roles/tomcat_common/templates/etc_security_limits.d_tomcat.conf.j2
Move the task and variables to set kernel limits for the Tomcat process out of the `marmotta` role and into the `tomcat_common` role.
To set specific limits, e.g. for Marmotta or another Java application, one should modify the `host_vars` file for the relevant server.
=> Move Tomcat kernel limits task to tomcat_common role

ansible/roles/site_proxy/defaults/main.yml
Lower the default size of the NGINX disk cache for the site_proxy role from 6Gb to 5Gb. This role is likely to be deployed on AWS, where the default volume size is 8Gb, so 6Gb is not leaving a lot of room for other things on the filesystem.
=> Lower defult NGINX cache size

ansible/roles/pss/defaults/main.yml, ansible/roles/pss/templates/settings.local.yml.j2
This allows us to set X-Frame-Options for primary source sets.  Along with accompanying changes to [pss](https://github.com/dpla/primary-source-sets/pull/179) and [aws](https://github.com/dpla/aws/pull/47), it will allow OER commons to display an iframe of primary source sets.  OER commons indexes our sets in their educational resources discovery tool.
I have run a local deployment, and verified with curl. This addresses [ticket #8490](https://issues.dp.la/issues/8490).
=> add configuration for pss x-frame-options

ansible/roles/marmotta/defaults/main.yml, ansible/roles/marmotta/tasks/main.yml, ansible/roles/tomcat_common/defaults/main.yml, ansible/roles/tomcat_common/tasks/main.yml, ansible/roles/tomcat_common/templates/etc_default_tomcat7.j2
- Add option to install Java JDK for the `tomcat` role. The JDK has tools for profiling.
- Optionally enable [JMX](https://en.wikipedia.org/wiki/Java_Management_Extensions) extensions for Tomcat's JVM
- Parameterize the Marmotta repository location and archive file checksum, so that it's possible to install your own build of Marmotta.
I think that these should be left as three commits.
Please don't merge this until we've confirmed that the `JAVA_OPTS` are adequate. I wanted to submit this for discussion first.
Note that the Tomcat changes are distinct from the Marmotta changes so that they can be applied to any Tomcat server in our infrastructure.
=> Add Tomcat and Marmotta features for profiling and custom packages

ansible/roles/frontend/templates/settings.local.yml.j2
Remove un-needed frontend setting related to searching for exhibitions in elasticsearch.
This addresses [ticket #7579](https://issues.dp.la/issues/7579) and relates to [frontend PR#131](https://github.com/dpla/frontend/pull/131).
=> remove un-needed setting for frontend exibitions elasticsearch

ansible/ingestion
I've had this change sitting around for a while without committing it. It has worked fine with my VMs (where I had them in a `host_vars` file, but the effect should be the same).
=> Add more kernel param vars to dev2 in inventory

ansible/roles/api/tasks/main.yml
Add sequence number parameters to the `update-rc.d` command that is called in order to make symbolic links for `delayed_job`'s init script. This makes it explicit that it should start after PostgreSQL. Just to give the other daemons some breathing room and to hopefully aid troubleshooting, I've also caused delayed_job to start after Rails.
=> Add sequence nums to update-rc.d for delayed_job

ansible/roles/ec2_swapper/defaults/main.yml, ansible/roles/ec2_swapper/tasks/main.yml, ansible/roles/ec2_swapper/tasks/needs_swap.yml
* Change method of allocating swap file to be less error-prone
* More effectively and safely skip over operations if swap is already active
The specific issue with the old way of allocating swapfile space, with `fallocate`, was that it was producing files with "holes." As mentioned in the comment, you can see http://www.faqs.org/docs/linux_admin/x1762.html for the recommended way with `dd`.
The `main.yml` playbook now skips over a whole range of tasks that are unnecessary if swap is already active on the instance. This should also handle legacy systems pretty well which might have had swap volumes on devices other than `/dev/xvdb`.
=> Improve ec2_swapper role

ansible/roles/ec2_swapper/tasks/needs_swap.yml
Fix the usage of the `mount` module in the `ec2_swapper` role so that it removes Ubuntu's `fstab` entry for `/mnt` when it unmounts it.  (The Ansible documentation is actually wrong about the difference between "unmounted" and "absent!")
Also remove the unnecessary `file` task to create the `/swap` directory, because the `mount` module will create it lower down in the file with `state=mounted`.
=> Fix mount / unmount in ec2_swapper role

ansible/roles/marmotta/tasks/main.yml
Remove a `template` task that was causing errors due to its file being missing in the `marmotta` role.
Management of a kernel parameters file was moved to the `tomcat_common` role in commit caab9bef6a25 on 2016-09-21.  The `template` task for this file was left in the `marmotta` role although it had been copied to `tomcat_common`.  The template file had been moved and deleted from the `marmotta` role.
=> Remove unwanted template task from marmotta role

ansible/roles/api/templates/etc_nginx_sites-available_api.j2
Write in a `location` directive for `/qa` in the NGiNX configuration only if the contentqa engine is enabled.
=> Fix API's nginx config: show /qa only if enabled

ansible/group_vars/all.dist, ansible/roles/api/templates/database.yml.j2, ansible/roles/api/templates/dpla.yml.j2, ansible/roles/elasticsearch/templates/elasticsearch.yml.j2, ansible/roles/frontend/templates/database.yml.j2, ansible/roles/frontend/templates/etc_nginx_sites-available_frontend.j2, ansible/roles/frontend/templates/settings.local.yml.j2, ansible/roles/ingestion_app/templates/database.yml.j2, ansible/roles/loadbalancer/templates/haproxy.cfg.j2, ansible/roles/postgresql/templates/pg_hba.conf.j2, ansible/roles/pss/templates/database.yml.j2, ansible/roles/site_proxy/templates/etc_nginx_sites_available_site-proxy.j2
Add a new variable, `all_in_one_hosts`, which governs whether each host in the inventory is self-contained, with no dependencies on other servers. This defaults to False, so no changes should be necessary for typical developer usage. This is for particular DPLA-specific use cases, like QA, and is not relevant to either production or development VM environments.
Also normalize some of the dict variable dereferencing syntax throughout various files, for a cleaner look, and for consistency. For example, change `groups['cms']` to `groups.cms`.
=> Add new variable for all-in-one hosts

ansible/roles/dbnode/tasks/main.yml
Fix the command to assign hosts to a BigCouch cluster so that only the local host is assigned when `all_in_one_hosts` is True.
This was left out of 918cd2e
=> Fix BigCouch cluster assignment, all-in-one hosts

ansible/roles/common/templates/hosts.j2, ansible/roles/common_sitenode/templates/etc_nginx_conf.d_trustedproxyips.j2
Fix more issues with configuration files when all_in_one_hosts is true. The `/etc/hosts` file and the NGiNX trusted proxy IPs file should just use the single inventory host instead of iterating through an inventory group.
=> Fix more all_in_one_hosts issues

README.md, ansible/roles/api/files/build_api.sh, ansible/roles/api/tasks/deploy.yml, ansible/roles/frontend/files/build_frontend.sh, ansible/roles/frontend/tasks/deploy.yml, ansible/roles/pss/files/build_pss.sh, ansible/roles/pss/tasks/deploy.yml
* Fix various deployments to honor our new strategy of using `Gemfile.lock` as it was intended.
* Provide `clean_*` variables for more roles, to allow build directories to be cleared.
* Update `README.md` with advice on using the `clean_*` variables. Also remove some  information that is misleading because it is incomplete. It should be covered elsewhere.
The changes here are to fix problems with Ruby gems being upgraded out from under us and breaking deployments. To keep ourselves from having to diligently pin random gems in our Gemfiles, we have decided to use Gemfile.lock files for their intended purpose. We must therefore stop removing Gemfile.lock before we do a `bundle install`.
The heidrun and frontend applications are exceptions. (Heidrun is deployed in the ingestion_app role.) …
=> Fix deployment gem issues

ansible/roles/common/templates/hosts.j2
The bad variable name `h` was causing a playbook error.
=> Fix /etc/hosts variable for current inventory hostname

ansible/group_vars/all.dist, ansible/roles/loadbalancer/templates/haproxy.cfg.j2, ansible/roles/site_proxy/defaults/main.yml, ansible/roles/site_proxy/templates/etc_nginx_sites_available_site-proxy.j2, ansible/roles/site_proxy/templates/robots.txt.j2
* Add comments to clarify the assignment of port numbers
* Fix `haproxy` configuration: remove hardcoded `server` parameters and write the frontend SSL configuration only when it's appropriate to do so.
* Optionally disallow spidering even in production
* Make all NGiNX `upstream` directives consistent in the `site_proxy` role.
Addresses https://digitalpubliclibraryofamerica.atlassian.net/browse/DT-566
=> Fix and improve the ability to operate all-in-one servers

ansible/roles/frontend/tasks/main.yml
This package is required for `rbenv` to compile Ruby with SSL support, which is necessary when running `bundle install`. There seems to have been a recent change (within the last week) in an Ubuntu package's dependencies that has stopped `libssl-dev` from being installed without our explicitly requesting it.
=> Add assertion of libssl-dev package, for frontend

README-ingestion2.md, README.md, Vagrantfile.dist, Vagrantfile.ingestion2, ansible/roles/api/defaults/main.yml, ansible/roles/common/files/etc_default_sysstat, ansible/roles/common/files/ssh_config, ansible/roles/common/tasks/main.yml, ansible/roles/common/templates/munin-node.conf.j2, ansible/roles/common_php/files/etc_logrotate.d_php5-fpm, ansible/roles/dbnode/files/build_libicu48.sh, ansible/roles/dbnode/files/libicu48, ansible/roles/dbnode/tasks/main.yml, ansible/roles/frontend/defaults/main.yml, ansible/roles/postgresql/defaults/main.yml, ansible/roles/pss/defaults/main.yml, ansible/roles/pss/tasks/main.yml, ansible/roles/site_proxy/defaults/main.yml
Update README files with updated installation instructions.
Update Vagrantfiles with new vagrant box names, and more memory allocation for the 'loadbal' VM.
Update 'common' role with changes to configuration files that coordinate with new package versions.
Update 'dbnode' role to work around broken dependency in 'bigcouch' package that was intended for Ubuntu 12.04.
Update 'pss' role to install libssl-dev dependency that is required by rbenv's build of Ruby 2.1. There must have been a depcndency cascade in Ubuntu 12.04 that caused it to be installed previously, whereas it was missing under 14.04.
It seems like there is more memory being allocated on these VMs with Ubuntu 14.04, which can lead to out-of-memory situations; so reduce memory usage by the following means:
* Lower the default …
=> Upgrade Ubuntu to 14.04 LTS

ansible/templates/variables.j2
Add templates/variables.j2, with inline usage instructions.
Reviewers should be able to try this out on a vm or wherever.
=> Add template for debugging variables

ansible/roles/common_php/files/etc_init_php5-fpm.conf, ansible/roles/common_php/tasks/main.yml
The upstart (init) configuration file for the php5-fpm package in Ubuntu 14 fails to respawn the php-fpm master process when it's killed with SIGKILL or (presumably) segfaults or dies due to some other reason.
For our purposes, we only want a SIGTERM or maybe SIGINT to be considered an intentional stop signal that signifies success. We also want to make sure that stale child processes are killed off before trying to restart php-fpm, because they'll be holding on to the socket files, preventing the service from starting.
This fixes https://digitalpubliclibraryofamerica.atlassian.net/browse/DT-1230
=> Fix failure of php-fpm to be respawned by upstart

ansible/roles/ec2_swapper/tasks/needs_swap.yml, ansible/roles/site_proxy/templates/etc_nginx_sites_available_site-proxy.j2
Set Host HTTP header in site proxy NGINX configuration when the SSL site proxy is not behind a loadbalancer (`siteproxy_self_ssl`).  Otherwise, the Host ends up being `dpla_portal` because that's the name of the`upstream` specified by `proxy_pass`.
Add back the task in the `ec2_swapper` role that checks that the `/swap` directory exists. This was removed in 62631a563a30 with the assumption that a later `mount` task would ensure its existence; overlooking the fact that the `mount` task is not run on a t2 or m4 instance.
These two commits should not be squashed.
=> Two little fixes

ansible/roles/omeka/templates/application_config_config.ini.j2
Have the Exhibitions Omeka application use a specific name for its session cookie. This allows us to better control the forwarding and filtering of HTTP headers in a caching proxy (specifically, CloudFront).
=> Have Exhibitions set specific session name

ansible/roles/site_proxy/templates/etc_nginx_sites_available_site-proxy.j2
Remove ineffective attempt at excluding bad bots in the site_proxy NGINX configuration. It blocked a seemingly random and very small number of bots by user-agent. Using this methodology it would be impossible to keep the list fresh, and, indeed, it's never been maintained. Besides, it assumes that "bad bots" are identifying themselves honestly.
=> Remove "bad bot" exclusion, site proxy Nginx config

ansible/roles/api/tasks/deploy.yml, ansible/roles/frontend/tasks/deploy.yml, ansible/roles/pss/tasks/deploy.yml, ansible/roles/thumbp/tasks/main.yml
Fix an oversight in the `thumbp` role, where a re-created `thumbp` user account would result in `/var/log/thumbp/thumbp.log` no longer being writable after a "clean" deployment, which would cause `thumbp` not to be able to start again.  (Solution: recursively ensure log directory ownership.)
Introduce the `clean_rbenv` variable, which can be used to delete a Rails application's Rbenv in order to clean it out, or to recompile C extensions from scratch; useful, for example, after an o/s upgrade.
=> Improve "clean" deployments, various apps

ansible/development, ansible/playbooks/dev_webapps.yml, ansible/playbooks/uv.yml, ansible/playbooks/uv_development.yml, ansible/playbooks/uv_production.yml, ansible/playbooks/uv_staging.yml, ansible/production_all.yml, ansible/roles/frontend/files/build_frontend.sh, ansible/roles/site_proxy/templates/etc_nginx_sites_available_site-proxy.j2, ansible/roles/uv/defaults/main.yml, ansible/roles/uv/files/build_uv.sh, ansible/roles/uv/files/copy_local_app.sh, ansible/roles/uv/tasks/clean.yml, ansible/roles/uv/tasks/deploy.yml, ansible/roles/uv/tasks/main.yml, ansible/staging_all.yml
Add `uv` role for Universal Viewer, and update NGINX configuration to serve the Javascript under `/uv`.
This changeset interacts with ongoing changes being made in the `frontend` app, so it shouldn't be merged until everything is synced up between `automation` and `frontend`.
To test, try running the role in your development VMs. You can run `ansible-playbook` like this:
```
ansible-playbook -u <you> -i development playbooks/dev_webapps.yml -e 'level=development'
```
If you need to deploy it again from scratch you can run the same playbook with `-e 'level=development clean_uv=true' -t uv` and save some time.
Let me know if you get an error from the `npm install` step in `build_uv.sh` saying "Fatal error in ../deps/v8/src/heap/store-buffer.cc" and "CHECK(object->IsHeapObject()) Failed". …
=> Add Universal Viewer

ansible/playbooks/reboot_siteproxy.yml
Change siteproxy reboot to forego de-registering and re-registering instances, because we've started using Application Load Balancers and Ansible 1.9, which we're still using, does not support an ALB's target groups.
See FIXME note in reboot_siteproxy.yml.
=> Fix siteproxy reboot for ALB

ansible/files/install_aws_cli.sh, ansible/files/install_python_tools.sh, ansible/roles/jenkins/defaults/main.yml, ansible/roles/jenkins/files/etc_init.d_jenkins, ansible/roles/jenkins/files/etc_logrotate.d_jenkins, ansible/roles/jenkins/handlers/main.yml, ansible/roles/jenkins/tasks/main.yml, ansible/roles/jenkins/templates/aws_config.j2, ansible/roles/jenkins/templates/etc_default_jenkins.j2, ansible/roles/pss/tasks/deploy.yml
Add a `jenkins` role to configure a Jenkins master server.
Add a generalized `pyenv` installer.
Additionally (as a separate commit), add a condition to decide whether to copy the SSH key for deployment of the private assets deployed with the Primary Source Sets application.
=> Add jenkins

ansible/playbooks/swapper.yml, ansible/roles/ec2_swapper/tasks/needs_swap.yml
* Do not use instance store volumes at all. They go away if you stop and start an instance. (As distinct from restarting.)
* Add playbook
=> Fix ec2_swapper role

ansible/ansible.cfg
Add a local roles path to the Ansible configuration file, so that you can have site-specific roles.
=> Add local roles path to ansible config

ansible/roles/thumbp/tasks/clean.yml
Get rid of the task that removes the whole `thumbp` account in `clean.yml` in the `thumbp` role. This is not necessary and causes a problem with file permissions upon redeployment.
Tested by redeploying with `-e 'clean_thumbp=yes'` repeatedly in the local VM environment.
=> Forego removal of "thumbp" account in "clean"

ansible/files/install_python_tools.sh, ansible/roles/jenkins/defaults/main.yml, ansible/roles/jenkins/tasks/main.yml
Update Python installations to support multiple versions.
Necessary because we need 2.7 for running Ansible (in the Jenkins role), but version 3 for running some Ingestion3-related utilities.
See https://digitalpubliclibraryofamerica.atlassian.net/browse/DT-1899
=> Update Python tools for Jenkins and Ingestion 3 use cases

ansible/roles/pss/tasks/deploy.yml
Improve the PSS deployment using the "local source" option so that it's easier to simulate the production environment with the development VMs.
The old method, copying the configuration files from the developer's source code working copy, was confusing, because they're normally written from the .j2 templates. If you want to use "local source" and also have config files that are similar to what you'd get in production, it's easier to manage that by updating your `group_vars/development` file with the settings you want.
=> Improve PSS deployment with local source

ansible/playbooks/package_upgrade.yml
In package_upgrade.yml, assert that aptitude is present, because it's
possible for it not to be in Ubuntu 16. The version of Ansible we still
use requires aptitude and won't fall back to apt-get.
=> Ensure aptitude installation for package upgrades

README.md, Vagrantfile.dist
I'm really sorry about this, but I had one of the VMs using the wrong Virtualbox box. I'd been playing around with Ubuntu 16 but ended up going back to 14 for the Elasticsearch box in my local `Vagrantfile`, and didn't make the corresponding fix to `Vagrantfile.dist`.
=> Fix incorrect VM box in Vagrantfile

ansible/roles/api/templates/dpla.yml.j2
Cqai3 boxes shouldn't have the reports link because they don't work.
There's a feature in the platform-cqa app that turns them off. 
Here's the deployment side of it.
=> Added switch for hiding reports link.

ansible/roles/common/tasks/main.yml, ansible/roles/common/templates/hosts.j2
These commits fix an annoyance with running the `common` role.
The `Update hosts file` task in that role has been the most error-prone task in the whole `automation` project for a long time. You couldn't run the `common` role on just one host without commenting that task out. There were also frequent errors due to different EC2 instance types having different ethernet interface names.
This changeset circumvents these problems by using the name resolver in an environment where the hosts are on a network with DNS for all of the hosts. There's no more need to interrogate all of the hosts in order to find their IP addresses and add them to `/etc/hosts`.
=> Fix hosts file w resolvconf
