dpla/automation

ansible/roles/frontend/defaults/main.yml
ansible/roles/frontend/files/build_frontend.sh
ansible/roles/frontend/tasks/deploy.yml
ansible/roles/frontend/vars/development.yml.dist

Reverts dpla/automation#45; per discussion with @markbreedlove via email.

Revert "Improve frontend private asset handling"

---

ansible/roles/frontend/templates/settings.local.yml.j2
ansible/roles/frontend/vars/development.yml.dist
ansible/roles/frontend/vars/production.yml.dist
ansible/roles/frontend/vars/staging.yml.dist

Set up S3 configuration variables for frontend [refs #7734]

---

.travis.yml
README.md

* Checks syntax of playbooks
* Runs ansible-lint on playbooks

Add Travis-CI configuration

---

Vagrantfile.ingestion2
ansible/roles/ingestion_app/defaults/main.yml
ansible/roles/ingestion_app/files/build_ingestion.sh
ansible/roles/ingestion_app/files/copy_local_app.sh
ansible/roles/ingestion_app/tasks/deploy.yml

See dpla/heidrun#21. I still need to test this, but I wanted to push up and share my changes. I'll try to test this later today.

Support new vendored deployment for mappings

---

ansible/roles/marmotta/files/tunedb.sh
ansible/roles/marmotta/tasks/main.yml

This is implemented as a shell script for maximum flexibility in the future.
See https://digitalpubliclibraryofamerica.atlassian.net/wiki/display/TECH/Index+performance+with+high+context+counts

Add Marmotta database tuning script

---

Vagrantfile.dist
ansible/roles/omeka/defaults/main.yml
ansible/roles/omeka/files/build_exhibitions.sh
ansible/roles/omeka/files/copy_local_app.sh
ansible/roles/omeka/tasks/deploy.yml

This addresses ticket #7822 https://issues.dp.la/issues/7822

Enable deployment of exhibitions from local source

---

ansible/roles/api/files/build_api.sh
ansible/roles/frontend/files/build_frontend.sh
ansible/roles/ingestion_app/files/build_ingestion.sh
ansible/roles/omeka/files/build_exhibitions.sh
ansible/roles/wordpress/files/build_wordpress_remote.sh

This adds `echo` statements to shell scripts that build our projects, to make troubleshooting less time-consuming.

Add logging for build scripts

---

ansible/roles/postgresql/defaults/main.yml
ansible/roles/postgresql/templates/postgresql.conf.j2

* Parameterize maintenance_work_mem
* Turn synchronous_commit off.  This seems safe given our requirements
and its low level of risk to our operations.
* Turn on logging of all queries that create temporary files.

Improve some PostgreSQL parameters

---

ansible/roles/frontend/defaults/main.yml
ansible/roles/frontend/templates/settings.local.yml.j2

See https://github.com/dpla/frontend/pull/62
This adds a parameter that is used by the code in that PR.
If that is merged, then this should be, too.

Add configuration of frontend/bookshelf max pages

---

ansible/roles/marmotta/templates/system-config.properties.j2
ansible/roles/marmotta/templates/system-meta.properties.j2

Add sparql.timeout.type and sparql.timeout.description to system-meta.properties.

Add sparql.timeout vars to Marmotta

---

ansible/roles/pss/defaults/main.yml
ansible/roles/pss/files/build_pss.sh
ansible/roles/pss/tasks/main.yml
ansible/roles/pss/templates/settings.local.yml.j2

Update the configuration of the app, following recent changes.

Update Primary Source Sets configuration

---

ansible/roles/api/files/build_api.sh
ansible/roles/frontend/files/build_frontend.sh
ansible/roles/ingestion_app/files/build_ingestion.sh

Adds detailed logging, particularly for Bundler's installation of dependencies.

Improve logging for build scripts for Ruby apps

---

ansible/roles/pss/defaults/main.yml
ansible/roles/pss/templates/settings.local.yml.j2

* Add pss_contact_email variable for pss role
* Add Wordpress and Exhibitions settings

Add settings and variables to pss settings.local.yml

---

ansible/roles/pss/defaults/main.yml
ansible/roles/pss/templates/settings.local.yml.j2

Add tags config setting to primary source sets.

add pss tags settings

---

ansible/roles/ingestion_app/defaults/main.yml
ansible/roles/ingestion_app/templates/config_settings.local.yml.j2

Add a parameter for the read_timeout setting that was recently added to Krikri.
See
https://github.com/dpla/KriKri/commit/c8a4c3596c95ef0800dc27f06421e3642ebe4754

Add ingestion app Marmotta read_timeout setting

---

ansible/roles/ingestion_app/defaults/main.yml
ansible/roles/ingestion_app/templates/config_settings.local.yml.j2

Add ingestion_app_log_level, to control the logging level of the ingestion application.
See
https://github.com/dpla/heidrun/commit/61bd30e1b05575aa1cb6101040e574e711d00159

Add heidrun log_level variable

---

README.md

Add a little note about an old change to Vagrantfile for `config.ssh.insert_key = false`, and fix some formatting.

Add note and fix some formatting in README.md

---

ansible/roles/omeka/tasks/deploy.yml

Addresses https://issues.dp.la/issues/7805

Remove copying of private keys for exhibition-assets

---

ansible/roles/pss/templates/settings.local.yml.j2

This sets up the configuration necessary for the change introduced in https://github.com/dpla/primary-source-sets/pull/166

Configure pss for memcache caching

---

ansible/playbooks/dbnodes.yml
ansible/playbooks/elasticsearch.yml
ansible/playbooks/reboot_dbnodes.yml
ansible/playbooks/reboot_siteproxy.yml
ansible/playbooks/siteproxy.yml

Addresses https://issues.dp.la/issues/7831

Add ignore_errors property to wait_for tasks

---

requirements.txt

Pin them to recommended and known-good versions.

Pin requirements in requirements.txt

---

ansible/production_all.yml
ansible/staging_all.yml

Improve staging_all.yml and production_all.yml.  Add role-level tags and add an empty play to gather facts for all hosts as insurance against undefined variables.

Improve and fix two top-level playbooks

---

ansible/roles/common_sitenode/templates/etc_nginx_conf.d_trustedproxyips.j2
ansible/roles/loadbalancer/templates/haproxy.cfg.j2
ansible/roles/postgresql/tasks/main.yml
ansible/roles/site_proxy/templates/etc_nginx_sites_available_site-proxy.j2

Add comments. Change one task not to report "changed".

Minor cosmetic improvements

---

ansible/roles/elasticsearch/defaults/main.yml
ansible/roles/elasticsearch/tasks/main.yml

Swap out Oracle JDK7 for Open JDK7

Update JDK source

---

ansible/roles/common_php/templates/php.ini.j2
ansible/roles/omeka/templates/application_config_config.ini.j2
ansible/roles/omeka/templates/etc_nginx_sites_available_omeka.j2
ansible/roles/pss/templates/etc_nginx_sites-available_pss.j2
ansible/roles/site_proxy/templates/etc_nginx_sites_available_site-proxy.j2
ansible/roles/wordpress/templates/etc_nginx_sites_available_wordpress.j2
ansible/roles/wordpress/templates/etc_php5_fpm_pool.d_wp.conf.j2

Increase file upload maximum file size settings in Nginx and PHP configurations.

Increase upload maximum file size settings

---

ansible/roles/api/templates/dpla.yml.j2

See https://github.com/dpla/platform/pull/54

Change field boosts for ES 6
